# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'exampleRIBs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RIBs'
pod 'Reusable'
pod 'SnapKit', '~> 4.0.0'
pod 'RxCocoa'

  # Pods for exampleRIBs

  target 'exampleRIBsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'exampleRIBsUITests' do
    # Pods for testing
  end

end
